#Having the lambda x: x % 100 == 1 function, use filter() to apply it to the list generated by
# range(0, 1000, 100). 

    
x = list(range(0, 1000, 100))
mylamb = filter(lambda x: x % 100 == 1, x)
print(list(mylamb))